add pys & timeago.js
parro-it/awesome-micro-npm-packages pull request #29
Opened 2016-09-18 07:58 UTC by hustcc

`pys ` is a ~700b javascript library to engance String.substring / Array.slice with python slice style.

`timeago.js` is a tiny(~1.7kb) library used to format date with `*** time ago` statement. eg: '3 hours ago'. No dependency & localization & tiny.

2016-09-18 09:44 UTC, parro-it commented
Thank you, do you mind to change the timeago url to the GitHub repo?

2016-09-18 10:26 UTC, hustcc commented
@parro-it no problem ^_^~

2016-09-19 05:06 UTC, parro-it requested changes
Test

2016-09-19 06:48 UTC, hustcc commented
What's this ?

2016-09-19 07:05 UTC, parro-it commented
Sorry, I just tested the new GH review feature...

2016-09-22 14:37 UTC, hustcc commented
So, how to do with it ?

2016-09-22 14:38 UTC, parro-it approved these changes

2016-09-22 14:39 UTC, parro-it commented
There is nothing special to do, I'm just testing the features... just change the repo as discussed above & I'll merge the PR

2016-12-11 10:51 UTC, parro-it commented
Any news?

2016-12-12 01:29 UTC, hustcc commented
Done, very sorry~^^

2016-12-12 03:06 UTC, parro-it commented
No worries, thank you for the contribution :smile:

2016-12-12 03:06 UTC, merged